#!/usr/bin/env bash


#############################################################################
# Constants
#############################################################################

# ultra settings from 7z(1)
SEVENZIP_OPT="-t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on"
REQUIRED_TOOLS="stat readlink 7z split"
MAX_UPLOAD_SIZE="9216"


#############################################################################
# Variables
#############################################################################

arch_cmd="7z a $SEVENZIP_OPT"
src_path=
output_dir="/shared/tmp"
archive=


#############################################################################
# Functions
#############################################################################

function die
{
	echo -e "$@"
	exit 1
}


function usage
{
	die 	"usage:\n   $0 DIR\nor $0 FILE"
}


function die_if_missing_tools
{
	missing_tools=

	for i in $REQUIRED_TOOLS ; do
		which $i > /dev/null || missing_tools="$i $missing_tools"
	done

	[[ -n $missing_tools ]] && \
		die "These tools are missing: $missing_tools"
}


#############################################################################
# Script
#############################################################################

die_if_missing_tools

[[ -n $1 ]] || usage

src_path=$(readlink -f $1)

if [[ -f $src_path || -d $src_path ]] ; then
	archive="${output_dir}/$(basename $src_path).7z"
	arch_cmd="$arch_cmd $archive $src_path"
else
	die "$src_path is not a dir nor a file"
fi

eval $arch_cmd
